INSERT INTO BOARD_USER
VALUES (SQ_BOARD_USER.NEXTVAL, '이산하', 'D', 'D', '설명글', 'USER',
        'NULL', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, 'N', NULL);
INSERT INTO BOARD_USER
VALUES (SQ_BOARD_USER.NEXTVAL, '두번째이산하', 'S', 'S', '설명글', 'USER',
        'NULL', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, 'N', NULL);


INSERT INTO NEIGHBOR
VALUES (SQ_NEIGHBOR.NEXTVAL, 1, 2, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, 'N', NULL);


INSERT INTO BOARD
VALUES (SQ_BOARD.NEXTVAL, '제목', '<p>컨텐츠<p>', 0, 1, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, 'N', NULL);
INSERT INTO BOARD
VALUES (SQ_BOARD.NEXTVAL, '제목', '<p>컨텐츠<p>', 0, 2, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, 'N', NULL);

COMMIT;